// <auto-generated />
using System;
using Elemental.FormBuilder.Code;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elemental.FormBuilder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210504144620_MandatoryFormId")]
    partial class MandatoryFormId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Elemental.FormBuilder.Form", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FormID");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            FormID = 1,
                            Description = "A form for testing.",
                            Title = "Test Form"
                        });
                });

            modelBuilder.Entity("Elemental.FormBuilder.FormField", b =>
                {
                    b.Property<int>("FormFieldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DropdownOptionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FormFieldID");

                    b.HasIndex("FormID");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            FormFieldID = 1,
                            Extension = "NAME",
                            Field = "Name",
                            FieldType = "Text",
                            FormID = 1,
                            Mandatory = true,
                            MaxLength = 100,
                            Section = "Basic info"
                        },
                        new
                        {
                            FormFieldID = 2,
                            Extension = "DESC",
                            Field = "Description",
                            FieldType = "Text",
                            FormID = 1,
                            Mandatory = false,
                            MaxLength = 400,
                            Section = "Basic info"
                        },
                        new
                        {
                            FormFieldID = 3,
                            Extension = "DT",
                            Field = "Creation Date",
                            FieldType = "Date",
                            FormID = 1,
                            Mandatory = true,
                            Section = "Basic info"
                        },
                        new
                        {
                            FormFieldID = 4,
                            Extension = "AMT",
                            Field = "Price",
                            FieldType = "Money",
                            FormID = 1,
                            Mandatory = true,
                            Section = "Price"
                        });
                });

            modelBuilder.Entity("Elemental.FormBuilder.FormField", b =>
                {
                    b.HasOne("Elemental.FormBuilder.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });
#pragma warning restore 612, 618
        }
    }
}
