// <auto-generated />
using System;
using AElemental.FormBuilder.Code;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AElemental.FormBuilder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210416134152_InitialDBMigration")]
    partial class InitialDBMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("AElemental.FormBuilder.FormField", b =>
                {
                    b.Property<int>("FormFieldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DropdownOptionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Extension")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.HasKey("FormFieldID");

                    b.ToTable("FormFields");
                });
#pragma warning restore 612, 618
        }
    }
}
